### PR TITLE
All non-pom changes to implement changes to support ImmutableVersion,…

### PR DESCRIPTION
**Pull request by kec**
… ImmutableEntity as sealed interfaces.

### CODE REVIEW

**Comment by kec** [comment]
Added a second commit to the pull request.

**Comment by kec** [comment]
Ok, resolved the NPE with ComponentProxy constructed from nids.

**Comment by kec** [comment]
Committed improvements to the lazy initialization of EntityProxy.

**Review by rbradley813 — APPROVED** [review]
Looks good and tests pass!

**Pull request merged**
